---
- name: Ensure tenant customer-xyz exists
  hosts:  localhost
  connection: local
  gather_facts: no
  aci_tenant:
    host: https://apic1.dcloud.cisco.com/
    username: admin
    password: C1sco12345

    tenant: customer-test
    description: Customer test
    state: present
